# This file defines the rules for the static site generator.
# It is the single source of truth for how the database content
# is converted into a static HTML website.

# -----------------------------------------
# Global Settings
# -----------------------------------------
settings:
  output_directory: "wwwroot"
  clean_before_build: false # For now, we will add to the existing wwwroot
  language_code: "en"

# -----------------------------------------
# Entity Definitions
# -----------------------------------------
entities:
  Worker:
    description: "An individual who assembles parts."
    repository: "WorkersRepository" # The PHP class to use for DB queries
    template: "frontend/workers/worker.tpl.php" # Show individual worker details
    path_schema: "/workers/{slug}/index.html" # e.g., /workers/candy-mama/index.html
    relationships:
      - type: "has_many_through_join_table"
        entity: "Photo"
        join_table: "workers_2_photos"
        local_key: "worker_id"
        foreign_key: "photo_id"
  Part:
    description: "A single component of a track."
    repository: "PartsRepository"
    template: "frontend/parts/part.tpl.php"
    path_schema: "/parts/{slug}/index.html"
    relationships:
      - type: "has_many_through_join_table"
        entity: "Photo"
        join_table: "parts_2_photos"
        local_key: "part_id"
        foreign_key: "photo_id"
  Moment:
    description: "A discrete animated event within the stop motion timeline."
    repository: "MomentRepository"
    template: "frontend/moments/moment.tpl.php"
    path_schema: "/moments/{slug}/index.html"
    relationships:
      - type: "has_many_through_join_table"
        entity: "Photo"
        join_table: "moments_2_photos"
        local_key: "moment_id"
        foreign_key: "photo_id"

# -----------------------------------------
# Index Page Definitions
# -----------------------------------------
indexes:
  WorkersIndex: # Use a map key instead of a list item
    name: "Workers Index"
    entity: "Worker"
    template: "frontend/workers/index.tpl.php" # This is the existing template
    path: "/workers/index.html"
  PartsIndex:
    name: "Parts Index"
    entity: "Part"
    template: "frontend/parts/index.tpl.php"
    path: "/parts/index.html"
  MomentsIndex:
    name: "Moments Index"
    entity: "Moment"
    template: "frontend/moments/index.tpl.php"
    path: "/moments/index.html"
