services:
  php:
    build: .
    container_name: mt3_php
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null  # Keep container running
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=dbmt3_test
      - DB_USER=root
      - DB_PASSWORD=mt3_test_pass
    networks:
      - mt3_network

  mysql:
    image: mysql:8.0
    container_name: mt3_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mt3_test_pass
      MYSQL_DATABASE: dbmt3_test
      MYSQL_USER: mt3_user
      MYSQL_PASSWORD: mt3_test_pass
    ports:
      - "3307:3306"  # Avoid conflict with local MySQL
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dbmt3.sql:/docker-entrypoint-initdb.d/00-schema.sql
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - mt3_network

networks:
  mt3_network:
    driver: bridge

volumes:
  mysql_data:
