ALTER TABLE parts
ADD COLUMN is_rail BOOLEAN DEFAULT FALSE,
ADD COLUMN is_support BOOLEAN DEFAULT FALSE,
ADD COLUMN is_track BOOLEAN DEFAULT FALSE,
ADD COLUMN no_track BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'If TRUE, this part is not part of any track';
